#!/usr/bin/env python3
# Kernora — AI Work Intelligence
# Elastic License 2.0 — commercial use requires agreement with kernora.ai
"""
Steering file generator — writes .kiro/steering/nora-*.md from analysis DB.

Called by:
  - kiro_agent_spawn.py when steering is stale (>24h)
  - daemon.py after each analysis cycle (optional)
  - Standalone: python3 steering_writer.py [--project /path/to/project]

Generates:
  ~/.kiro/steering/nora-patterns.md     (global — patterns from all sessions)
  ~/.kiro/steering/nora-decisions.md    (global — architectural decisions)
  ~/.kiro/steering/nora-antipatterns.md (global — things to avoid)
  .kiro/steering/nora-project.md        (project-local — if --project specified)

These files are automatically read by Kiro on every prompt, providing
persistent context without hooks. This is the highest-value Kiro integration.

SECURITY: reads from local SQLite only, writes to local filesystem only.
"""
import json
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

DB_PATH = Path.home() / ".kernora" / "echo.db"
GLOBAL_STEERING = Path.home() / ".kiro" / "steering"


def get_insights(limit: int = 50) -> list[dict]:
    """Fetch recent insights with non-empty analysis fields."""
    if not DB_PATH.exists():
        return []
    try:
        conn = sqlite3.connect(str(DB_PATH), timeout=5)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM insights ORDER BY analyzed_at DESC LIMIT ?",
            (limit,),
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_patterns() -> list[dict]:
    """Fetch patterns from the patterns table."""
    if not DB_PATH.exists():
        return []
    try:
        conn = sqlite3.connect(str(DB_PATH), timeout=5)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM patterns ORDER BY effectiveness DESC, created_at DESC LIMIT 30"
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_decisions() -> list[dict]:
    """Fetch decisions from the decisions table."""
    if not DB_PATH.exists():
        return []
    try:
        conn = sqlite3.connect(str(DB_PATH), timeout=5)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM decisions ORDER BY created_at DESC LIMIT 30"
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _parse_json_field(value: str) -> list:
    """Safely parse a JSON field that might be a string or already a list."""
    if not value:
        return []
    try:
        result = json.loads(value)
        return result if isinstance(result, list) else []
    except (json.JSONDecodeError, TypeError):
        return []


def write_patterns_steering(insights: list[dict], patterns: list[dict]):
    """Generate nora-patterns.md — reusable patterns and playbooks."""
    GLOBAL_STEERING.mkdir(parents=True, exist_ok=True)
    out = GLOBAL_STEERING / "nora-patterns.md"

    lines = [
        "---",
        "description: Patterns and playbooks learned from past coding sessions (auto-generated by Nora)",
        "globs: \"**/*\"",
        "---",
        "",
        "# Learned Patterns",
        "",
        "These patterns were extracted from your coding sessions by Nora.",
        "Kiro uses them to inform code generation and avoid reinventing solutions.",
        "",
    ]

    # From patterns table
    if patterns:
        lines.append("## Reusable Patterns")
        lines.append("")
        for p in patterns:
            lines.append(f"### {p.get('pattern', 'Unnamed pattern')}")
            if p.get("context"):
                lines.append(f"**When to use:** {p['context']}")
            if p.get("code_example"):
                lines.append(f"```\n{p['code_example']}\n```")
            if p.get("domains"):
                lines.append(f"**Domains:** {p['domains']}")
            lines.append("")

    # From insights — playbooks
    playbooks = []
    for ins in insights:
        pb = ins.get("playbook", "")
        if pb and len(pb) > 20:
            playbooks.append({"playbook": pb, "summary": ins.get("summary", "")})
    if playbooks:
        lines.append("## Playbooks")
        lines.append("")
        for i, pb in enumerate(playbooks[:10], 1):
            lines.append(f"### Playbook {i}: {pb['summary'][:80]}")
            lines.append(f"{pb['playbook']}")
            lines.append("")

    # From insights — reusable_patterns
    all_rp = []
    for ins in insights:
        rps = _parse_json_field(ins.get("reusable_patterns", "[]"))
        all_rp.extend(rps)
    if all_rp:
        lines.append("## Session-Derived Patterns")
        lines.append("")
        seen = set()
        for rp in all_rp:
            text = rp.get("pattern", "") if isinstance(rp, dict) else str(rp)
            if text and text not in seen:
                seen.add(text)
                context = rp.get("context", "") if isinstance(rp, dict) else ""
                lines.append(f"- **{text}**" + (f" — {context}" if context else ""))
        lines.append("")

    # From insights — knowledge domains
    all_domains = set()
    for ins in insights:
        domains = _parse_json_field(ins.get("knowledge_domains", "[]"))
        for d in domains:
            if isinstance(d, str) and d:
                all_domains.add(d.lower())
    if all_domains:
        lines.append("## Technology Domains")
        lines.append("")
        lines.append(", ".join(sorted(all_domains)))
        lines.append("")

    lines.append(f"\n*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    out.write_text("\n".join(lines))
    return out


def write_decisions_steering(insights: list[dict], decisions: list[dict]):
    """Generate nora-decisions.md — architectural decisions and rules."""
    GLOBAL_STEERING.mkdir(parents=True, exist_ok=True)
    out = GLOBAL_STEERING / "nora-decisions.md"

    lines = [
        "---",
        "description: Architectural decisions and project rules from past sessions (auto-generated by Nora)",
        "globs: \"**/*\"",
        "---",
        "",
        "# Architectural Decisions & Rules",
        "",
        "These decisions were extracted from your coding sessions by Nora.",
        "Kiro uses them to maintain consistency across code generation.",
        "",
    ]

    # From decisions table
    if decisions:
        lines.append("## Decisions")
        lines.append("")
        for d in decisions:
            lines.append(f"### {d.get('decision', 'Unnamed')}")
            if d.get("context"):
                lines.append(f"**Context:** {d['context']}")
            if d.get("rationale"):
                lines.append(f"**Rationale:** {d['rationale']}")
            if d.get("alternatives"):
                lines.append(f"**Alternatives considered:** {d['alternatives']}")
            lines.append("")

    # From insights — architectural_decisions
    all_ad = []
    for ins in insights:
        ads = _parse_json_field(ins.get("architectural_decisions", "[]"))
        all_ad.extend(ads)
    if all_ad:
        lines.append("## Session-Derived Decisions")
        lines.append("")
        seen = set()
        for ad in all_ad:
            decision = ad.get("decision", "") if isinstance(ad, dict) else str(ad)
            if decision and decision not in seen:
                seen.add(decision)
                context = ad.get("context", "") if isinstance(ad, dict) else ""
                lines.append(f"- **{decision}**" + (f" — {context}" if context else ""))
        lines.append("")

    # From insights — claude_md_rules (project conventions)
    all_rules = []
    for ins in insights:
        rules = _parse_json_field(ins.get("claude_md_rules", "[]"))
        all_rules.extend(rules)
    if all_rules:
        lines.append("## Project Rules (from CLAUDE.md analysis)")
        lines.append("")
        seen = set()
        for rule in all_rules:
            text = rule if isinstance(rule, str) else str(rule)
            if text and text not in seen:
                seen.add(text)
                lines.append(f"- {text}")
        lines.append("")

    lines.append(f"\n*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    out.write_text("\n".join(lines))
    return out


def write_antipatterns_steering(insights: list[dict]):
    """Generate nora-antipatterns.md — things to avoid."""
    GLOBAL_STEERING.mkdir(parents=True, exist_ok=True)
    out = GLOBAL_STEERING / "nora-antipatterns.md"

    lines = [
        "---",
        "description: Anti-patterns and mistakes to avoid, learned from past sessions (auto-generated by Nora)",
        "globs: \"**/*\"",
        "---",
        "",
        "# Anti-Patterns — Things to Avoid",
        "",
        "These anti-patterns were observed in past coding sessions.",
        "Kiro uses them to prevent repeating the same mistakes.",
        "",
    ]

    all_ap = []
    for ins in insights:
        aps = _parse_json_field(ins.get("anti_patterns", "[]"))
        all_ap.extend(aps)

    if all_ap:
        seen = set()
        for ap in all_ap:
            pattern = ap.get("pattern", "") if isinstance(ap, dict) else str(ap)
            if pattern and pattern not in seen:
                seen.add(pattern)
                impact = ap.get("impact", "") if isinstance(ap, dict) else ""
                fix = ap.get("fix", "") if isinstance(ap, dict) else ""
                lines.append(f"### {pattern}")
                if impact:
                    lines.append(f"**Impact:** {impact}")
                if fix:
                    lines.append(f"**How to avoid:** {fix}")
                lines.append("")
    else:
        lines.append("No anti-patterns recorded yet. Keep coding — Nora is watching.")
        lines.append("")

    # From insights — bugs (common error patterns)
    all_bugs = []
    for ins in insights:
        bugs = _parse_json_field(ins.get("bugs", "[]"))
        all_bugs.extend(bugs)
    if all_bugs:
        lines.append("## Common Bugs")
        lines.append("")
        seen = set()
        for bug in all_bugs:
            title = bug.get("title", "") if isinstance(bug, dict) else str(bug)
            if title and title not in seen:
                seen.add(title)
                fix = bug.get("fix", "") if isinstance(bug, dict) else ""
                sev = bug.get("severity", "") if isinstance(bug, dict) else ""
                lines.append(f"- **{title}**" + (f" [{sev}]" if sev else "") + (f" — Fix: {fix}" if fix else ""))
        lines.append("")

    lines.append(f"\n*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    out.write_text("\n".join(lines))
    return out


def generate_all():
    """Generate all steering files from current DB state."""
    insights = get_insights()
    if not insights:
        print("[nora] No insights in DB — skipping steering generation")
        return []

    patterns = get_patterns()
    decisions = get_decisions()

    files = []
    files.append(write_patterns_steering(insights, patterns))
    files.append(write_decisions_steering(insights, decisions))
    files.append(write_antipatterns_steering(insights))

    for f in files:
        print(f"[nora] Generated steering: {f}")
    return files


if __name__ == "__main__":
    generate_all()
